### ISSUE TITLE
RPC problem; getbalance is broken.

### ISSUE THREAD

**Issue by coldcity** [mintcoinproject/mintcoin#1]
On a mintcoind fresh from git checkout, with synced blockchain:

someone@somebox:~$ mintcoind listaccounts
{
    "" : 0.00000000,
    "gamebank" : 999999.00000000
}
someone@somebox:~$ mintcoind getbalance
999999.00000000
someone@somebox:~$ mintcoind getbalance gamebank
-9216810327147.70507812
someone@somebox:~$ mintcoind getbalance test
-9216811327146.70507812

The last two outputs are incorrect; getbalance gamebank should return 999999.0, and getbalance test should return 0.

**Comment by b1nary** [comment]
this should be first priority. Without getbalance you have to modify each service and script which is supposed to work with that value.

**Comment by mintcoinproject** [comment]
fixed, thanks.
